// Build step: wrap the compiled Tailwind CSS in a <style> snippet that Zesty
// includes verbatim.
//
// WHY: Zesty's stylesheet pipeline combines + compiles + minifies everything in
// styles/ into /site.css. Running Tailwind v4's already-compiled output (cascade
// @layer, @property, nested at-rules) through that pipeline MANGLES it — it drops
// @layer components and most utilities. A snippet is HTML, so it bypasses the CSS
// pipeline and is delivered as-is. The compiled CSS contains no "{{", so Parsley
// leaves it alone.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const css = readFileSync(resolve(root, "webengine/styles/tailwind.css"), "utf8");
const out = resolve(root, "webengine/views/components/styles.html");

const banner =
  "<!-- AUTO-GENERATED by tools/inline-css.mjs from src/tailwind.css — do NOT edit by hand.\n" +
  "     Inlined because Zesty's /site.css pipeline mangles Tailwind v4 output.\n" +
  "     Regenerate: npm run build:css -->";

writeFileSync(out, banner + "\n<style>\n" + css + "\n</style>\n");
console.log(`Wrote webengine/views/components/styles.html (${css.length} bytes of CSS inlined)`);
